require: rubocop-thread_safety
require: rubocop-rspec

inherit_from:
  - .rubocop_general.yml
  - .rubocop_rspec.yml
  - .rubocop-thread_safety.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/20160804143438_init_schema.rb'
    - 'vendor/cache/**/*'
