language: ruby
rvm:
  - 2.5.1
env:
  - DB=postgresql TRAVIS=true
addons:
  apt_packages:
    - rpm
before_install:
  - $($INIT)
  - rpm --help
  - bundle install

before_script:
  - gem update --system
  - gem --version
  - psql -c 'create database prometheus_test;' -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
