# frozen_string_literal: true
N_('Alexey Shabalin')
N_('Andrey Cherepanov')
N_('Andriy Stepanov')
N_('Anton Farygin')
N_('Denis Nazarov')
N_('Denis Smirnov')
N_('Dmitriy Kulik')
N_('Egor Vyscrebentsov')
N_('Eugene Prokopiev')
N_('Eugeny A. Rostovtsev')
N_('Igor Vlasenko')
N_('Igor Zubkov')
N_('Ildar Mulyukov')
N_('Lenar Shakirov')
N_('Michael Shigorin')
N_('Motsyo Gennadi')
N_('Mykola Grechukh')
N_('Radik Usupov')
N_('Valentin Rosavitskiy')
N_('Vitaly Lipatov')
N_('Vladimir Didenko')
N_('Ivan Zakharyaschev')
N_('Gleb Fotengauer-Malinovskiy')
N_('Vladimir D. Seleznev')
N_('Mikhail')
N_('Mikhail Efremov')
N_('Anton V. Boyarshinov')
N_('Ivan A. Melnikov')
N_('Grigory Ustinov')
N_('Anton Midyukov')
N_('Stanislav Levin')
N_('Yuri N. Sedunov')
N_('Sergey V Turchin')
N_('George V. Kouryachy')
N_('Aleksei Nikiforov')
N_('Dmitry V. Levin')
N_('Nikolay A. Fetisov')
N_('Valery Inozemtsev')
N_('Vladimir Lettiev')
N_('Alexey Gladkov')
N_('Evgenii Terechkov')
N_('Paul Wolneykien')
N_('Pavel Skrylev')
N_('Sergey Bolshakov')
N_('Andrew Savchenko')
N_('Andrey Bychkov')
N_('AEN')
N_('Denis Medvedev')
N_('Alexey Appolonov')
N_('Ruby Team')
N_('Nikolai Kostrigin')
N_('Kernel Bot')
N_('Pavel Moseev (Mars)')
N_('Konstantin A. Lepikhov')
N_('Oleg Solovyov')
N_('Alexei Takaseev')
N_('Cronbuild Service')
N_('Vitaly Chikunov')
N_('ptrnine')
N_('Alexander Makeenkov')
N_('Grigory Batalov')
N_('Alexander Myltsev')
N_('Alexey Tourbin')
N_('Kiriil A. Shutemov')
N_('Vitaly Kuznetsov')
